/**
 * Russian (ru) dictionaries, one entry per locale namespace.
 * Key sets mirror each namespace's zh/en dictionaries at the profiled
 * base commit; any key added upstream later falls back to en at lookup.
 */

export const RU_LABEL = 'Русский'

export const RU_DICTS: Record<string, Record<string, string>> = {
  'common': {
    'ok': 'ОК',
    'cancel': 'Отмена',
    'close': 'Закрыть',
    'copy': 'Копировать',
    'copied': 'Скопировано',
    'copy.failed': 'Не удалось скопировать',
    'copy.value': 'Копировать значение',
    'copy.json': 'Копировать JSON',
    'copy.path': 'Копировать путь',
    'copy.prettyJson': 'Копировать красивый JSON',
    'copy.compactJson': 'Копировать компактный JSON',
    'copy.optionsHint': '{action}; правый клик — варианты копирования',
    'retry': 'Повторить',
    'loading': 'Загрузка…',
    'load.failed': 'Не удалось загрузить',
    'submit': 'Отправить',
    'submitting': 'Отправка…',
    'next': 'Далее',
    'previous': 'Предыдущий',
    'skip': 'Пропустить',
    'delete': 'Удалить',
    'edit': 'Изменить',
    'save': 'Сохранить',
    'search': 'Поиск',
    'more': 'Ещё',
    'collapse': 'Свернуть',
    'expand': 'Развернуть',
    'back': 'Назад',
    'brand.localBuild': 'Локальная сборка DSH',
    'unknown': 'Неизвестно',
    'none': 'Нет',
    'truncated': 'Обрезано',
    'json.collapseNode': 'Свернуть узел JSON',
    'json.expandNode': 'Развернуть узел JSON',
    'json.label': 'JSON',
    'markdown.footnotes': 'Сноски',
    'markdown.truncatedCharacters': '… обрезано на {total} символах',
    'number.thousand': '{value} тыс.',
    'number.million': '{value} млн',
  },
  'settings.locale': {
    'language.title': 'Язык',
  },
  'settings.agentPreset': {
    'error': 'Не удалось загрузить пресеты агента.',
    'userTrust': 'Свой',
    'seatHint': 'Пресет агента для сессии, которую вы собираетесь начать',
    'headerHint': 'Пресет агента, с которым работает эта сессия; фиксируется при запуске',
    'nav': 'Пресеты агента',
    'sectionIntro': 'Пресет — это композиция плагинов, с которыми работает агент сессии: его инструменты, промпт и возможности. Скопируйте существующий пресет и настройте под себя или позвольте агенту составить его в режиме Creator.',
    'builtIn': 'Встроенные',
    'setDefault': 'Сделать пресетом по умолчанию',
    'view': 'Просмотр',
    'presetStandardName': 'Стандартный режим',
    'presetStandardDescription': 'Полноценный агент-программист: редактирование файлов, shell, поиск по файлам и в вебе, навыки, планирование, цели, субагенты и воркфлоу.',
    'presetPtcName': 'Режим кода',
    'presetMinimalName': 'Минимальный режим',
    'presetMinimalDescription': 'Агент-программист из двух инструментов: постоянный bash и str_replace_editor.',
    'presetCordisName': 'Режим Creator',
    'presetCordisDescription': 'Создан для разработки собственных пресетов: все возможности стандартного режима плюс инспекция на лету, эксперименты с плагинами и подсказки по созданию пресетов.',
    'duplicate': 'Дублировать',
    'duplicateUnavailable': 'В этой сборке нет каталога пресетов для записи',
    'delete': 'Удалить',
    'presetId': 'Идентификатор',
    'presetIdPlaceholder': 'my-agent',
    'displayName': 'Название',
    'displayNamePlaceholder': 'Показывается в выборе; по умолчанию — идентификатор',
    'inUse': 'Используется',
    'builtInGroup': 'Встроенные',
    'customGroup': 'Свои',
    'noDescription': 'Нет описания.',
    'brokenBadge': 'Не удалось загрузить',
    'brokenNoCopy': 'Пресет, который не удалось загрузить, нельзя дублировать',
    'copyOf': 'Копия из',
    'composition': 'Композиция (agent.cordis.yml)',
    'cancel': 'Отмена',
    'close': 'Закрыть',
    'retry': 'Повторить',
    'copyTitle': 'Дублировать пресет',
    'copyIntro': 'Пресет целиком копируется на этом компьютере. Идентификатор становится именем каталога и не меняется впоследствии; всё остальное редактируется в файлах самого пресета.',
    'create': 'Создать',
    'creating': 'Создание…',
    'creatorDraft': 'Составить свой пресет в режиме Creator',
    'openLocation': 'Открыть папку',
    'showLocation': 'Показать путь',
    'revealedPathLabel': 'Файлы пресета:',
    'idRequired': 'Укажите идентификатор пресета.',
    'idInvalid': 'Используйте строчные буквы, цифры и дефисы, начиная с буквы или цифры.',
    'idTaken': 'Пресет с таким идентификатором уже существует.',
    'deleteTitle': 'Удалить этот пресет?',
    'deleteDescription': 'Каталог пресета будет удалён. Сессии, которые уже работают на нём, продолжат работу; новые сессии не смогут его выбрать.',
    'deleteConfirm': 'Удалить',
    'deleting': 'Удаление…',
    'presetPtcDescription': 'Полноценный агент-программист без инструмента workflow; остальные инструменты доступны через SDK режима PTC, поэтому модель может объединять многошаговые операции в одну программу на TypeScript.',
    'switchRefused': 'Не удалось переключить на «{name}»: {reason}',
  },
  'approval': {
    'detail.aria': 'Детали запроса',
    'waiting': 'Ожидает одобрения',
    'escalation': 'Инструмент {toolName} запрашивает привилегированное выполнение',
    'reject': 'Отклонить',
    'allowOnce': 'Разрешить один раз',
  },
  'command': {
    'search.placeholder': 'Поиск…',
    'search.aria': 'Фильтр вариантов',
    'status.loading': 'Загрузка вариантов…',
    'status.applying': 'Применение…',
    'status.empty': 'Нет вариантов',
    'overlay.aria': 'Варианты /{command}',
    'listbox.aria': 'Совпадения /{command}',
    'notice.imagesUnsupported': '/{command} не принимает изображения; сначала удалите их',
  },
  'conversation': {
    'hint.plan': 'опишите вашу задачу, чтобы составить план',
    'hint.goal': 'опишите цель для длительной задачи',
    'hint.goal.active': 'цель активна — edit / pause / resume / clear',
    'placeholder.plan': 'опишите вашу задачу, чтобы составить план',
    'placeholder.default': 'Напишите агенту',
    'placeholder.unavailable': 'Сессия недоступна',
    'placeholder.parentOffline': 'Родительская сессия офлайн: отправка недоступна, но вы можете остановить выполнение',
    'placeholder.hero': 'Опишите, что вы хотите создать',
    'placeholder.workspace': 'Выберите рабочее пространство, чтобы начать',
    'placeholder.steerQueue': 'Cmd/Ctrl+Enter — отправить все сообщения из очереди',
    'input.commands': 'Команды',
    'input.stop': 'Остановить генерацию',
    'input.send': 'Отправить сообщение',
    'input.accessMode': 'Режим доступа, текущий: {name}',
    'image.dropTitle': 'Перетащите изображения сюда, чтобы добавить их',
    'image.dropDesc': 'До {count} изображений, по {size} каждое',
    'image.dropBlocked': 'Сейчас нельзя добавить изображения',
    'image.pending': 'Изображения ожидают отправки',
    'image.openOriginal': 'Открыть оригинал',
    'image.openOriginalLabel': '{label}, нажмите, чтобы открыть оригинал',
    'image.remove': 'Удалить изображение {name}',
    'image.scrollLeft': 'Прокрутить изображения влево',
    'image.scrollRight': 'Прокрутить изображения вправо',
    'image.original': 'Оригинал',
    'image.label': 'Изображение',
    'image.loadFailed': 'Не удалось загрузить изображение; нажмите, чтобы повторить',
    'image.loading': 'Загрузка изображения…',
    'image.preview': 'Просмотр оригинала',
    'image.closePreview': 'Закрыть просмотр оригинала',
    'image.unsupportedType': 'Поддерживаются только изображения PNG, JPG, WebP и GIF',
    'image.tooMany': 'Сообщение может содержать до {count} изображений',
    'image.fileTooLarge': 'Каждое изображение должно быть меньше {size}',
    'image.totalTooLarge': 'Суммарный размер изображений превышает {size}; удалите часть и повторите',
    'image.tooManyPixels': 'Разрешение изображения слишком высокое; сожмите его и повторите',
    'image.dimensionTooLarge': 'Стороны изображения не должны превышать {size}px; уменьшите его и повторите',
    'image.modelUnsupported': 'Текущая модель не поддерживает изображения; переключитесь на модель с их поддержкой',
    'image.sendFailed': 'Не удалось отправить изображения ({reason}); добавьте их заново и повторите',
    'context.aria': 'Использовано {percent} контекста',
    'context.used': 'контекста использовано',
    'context.system': 'Системный промпт',
    'context.tools': 'Инструменты',
    'context.messages': 'Сообщения',
    'settings.enter.title': 'Поведение Enter при занятости',
    'settings.enter.description': 'Только при занятости; Cmd/Ctrl+Enter использует другое поведение',
    'settings.enter.queue': 'В очередь',
    'settings.enter.steer': 'Отправить сразу',
    'access.preset.readOnly': 'Только чтение',
    'access.preset.workspaceWrite': 'Запись в рабочую папку',
    'access.preset.fullAccess': 'Полный доступ',
    'access.confirm.title': 'Включить «Полный доступ»?',
    'access.confirm.description': '«Полный доступ» уменьшает число этапов подтверждения и позволяет агенту напрямую выполнять больше действий, включая чувствительные операции, изменение файлов или внешние команды. Используйте его, только если доверяете текущей задаче.',
    'access.confirm.acknowledge': 'Я понимаю риски и хочу продолжить',
    'access.confirm.cancel': 'Отмена',
    'access.confirm.enable': 'Включить «Полный доступ»',
    'hero.headline': 'К неизведанному',
    'hero.preview': 'Предпросмотр',
    'hero.chooseWorkspace': 'Выбрать рабочее пространство',
    'session.hierarchy': 'Иерархия сессий',
    'todo.title': 'Задачи',
    'todo.progress.done': '{done} выполнено',
    'todo.progress.active': '{active} в процессе',
    'todo.progress.pending': '{pending} ожидает',
    'todo.rowTitle': 'Обновить список задач',
    'todo.completed': '{done}/{total} выполнено',
    'command.imagesUnsupported': '/{command} не принимает изображения; сначала удалите их',
    'ask.rowTitle': 'Задать вопрос',
    'ask.waiting': 'ожидание',
    'ask.cancelled': 'отменено',
    'ask.cancelledDetail': 'Этот набор вопросов был отменён до отправки ответов.',
    'ask.interrupted': 'прервано',
    'ask.interruptedDetail': 'Этот набор вопросов был прерван до отправки ответов.',
    'ask.answered': '{answered}/{total} отвечено',
    'ask.skipped': 'Не отвечено',
    'bash.running': 'Выполняется',
    'bash.failed': 'Ошибка',
    'bash.stopped': 'Остановлено',
    'row.running': 'Выполняется',
    'row.failed': 'Ошибка',
    'row.stopped': 'Остановлено',
    'row.input': 'ВВОД',
    'row.output': 'ВЫВОД',
    'row.inspect': 'Просмотр',
    'tool.title.search': 'Поиск',
    'tool.title.read': 'Чтение',
    'tool.title.bash': 'Bash',
    'tool.title.write': 'Запись',
    'tool.title.edit': 'Правка',
    'tool.title.code': 'Код',
    'tool.title.generic': 'Вызов инструмента',
    'tool.title.inspect': 'Просмотр',
    'tool.title.runCordis': 'Запустить плагин Cordis',
    'tool.title.stopCordis': 'Остановить плагин Cordis',
    'tool.title.removeCordis': 'Удалить плагин Cordis',
    'tool.title.pwsh': 'Pwsh',
    'tool.title.grep': 'Grep',
    'tool.title.glob': 'Glob',
    'tool.title.webSearch': 'Поиск',
    'tool.title.webFetch': 'Запрос',
    'diff.files.one': '{count} файл',
    'diff.files.other': '{count} файлов',
    'diff.collapseAria': 'Свернуть изменения',
    'diff.expandAria': 'Показать ещё {count} строк изменений',
    'diff.expandRest': '… ещё {count} строк',
    'read.window': 'Показано {shown} из {total} строк',
    'read.collapseAria': 'Свернуть содержимое',
    'read.expandAria': 'Показать ещё {count} строк',
    'read.expandRest': '… ещё {count} строк',
    'search.paths': '{shown} путей',
    'search.paths.truncated': 'Показано {shown} из {total} путей',
    'search.matches': '{shown} совпадений · {files} файлов',
    'search.matches.truncated': 'Показано {shown} из {total} совпадений · {files} файлов',
    'search.noResults': 'Ничего не найдено',
    'search.collapseAria': 'Свернуть результаты',
    'search.expandAria': 'Показать ещё {count} строк результатов',
    'search.expandRest': '… ещё {count} строк',
    'web.noResults': 'Ничего не найдено',
    'web.sourcesTruncated': 'Список источников обрезан',
    'web.http': 'HTTP',
    'web.contentTruncated': 'Содержимое обрезано',
    'details.running': 'Выполняется…',
    'queue.count': 'В очереди: {n}',
    'queue.image': 'Изображение в очереди сообщения',
    'queue.edit': 'Изменить сообщение из очереди',
    'queue.edit.unsupported': 'Содержит нетекстовый контент; редактирование пока не поддерживается',
    'queue.save': 'Сохранить сообщение из очереди',
    'queue.cancelEdit': 'Отменить редактирование',
    'queue.remove': 'Удалить сообщение из очереди',
    'queue.steer': 'Отправить сразу',
    'queue.steer.unavailable': 'Отправка сразу доступна только пока агент работает',
    'queue.editFailed': 'Не удалось изменить: сообщение могло уже начать отправляться.',
    'queue.removeFailed': 'Не удалось удалить: сообщение могло уже начать отправляться.',
    'queue.steerFailed': 'Не удалось отправить сразу. Повторите попытку.',
    'terminal.signal': 'сигнал {signal}',
    'terminal.exitCode': 'код выхода {code}',
    'terminal.running': 'Выполняется',
    'terminal.failed': 'Ошибка',
    'terminal.done': 'Готово',
    'terminal.noOutput': 'Нет вывода',
    'terminal.collapseAria': 'Свернуть вывод',
    'terminal.expandAria': 'Развернуть оставшиеся строки вывода ({n})',
    'terminal.expandRest': '… ещё строк: {n}',
    'terminal.sendInput': '(отправить ввод)',
    'terminal.session': 'Терминал {sessionId}',
  },
  'deliverables': {
    'produced.label': 'Создано',
    'produced.moreOne': '+ 1 файл',
    'produced.more': '+ {count} файлов',
    'produced.open': 'Открыть {name}',
    'produced.showInFolder': 'Показать в папке',
  },
  'goal': {
    'phase.active': 'Активная цель',
    'phase.paused': 'Приостановленная цель',
    'phase.blocked': 'Заблокированная цель',
    'objective.aria': 'Содержимое цели',
    'commandInput.aria': 'Ввод команды',
    'action.save': 'Сохранить цель',
    'action.cancel': 'Отменить правку',
    'action.pause': 'Приостановить цель',
    'action.resume': 'Возобновить цель',
    'action.edit': 'Изменить цель',
    'action.clear': 'Удалить цель',
  },
  'slash.menu': {
    'command': 'Команды',
    'skill': 'Навыки',
    'subagent': 'Субагенты',
    'loading': 'Загрузка…',
    'drill.aria': 'Обзор папки',
    'drill.hint': 'Обзор папки',
    'drill.key': 'Tab',
    'crumbs.aria': 'Навигация по папкам',
    'suggestions.aria': 'Возможные варианты по триггеру',
  },
  'job': {
    'count.live.one': '{count} фоновая задача выполняется',
    'count.live.other': '{count} фоновых задач выполняется',
    'count.idle.one': '{count} фоновая задача',
    'count.idle.other': '{count} фоновых задач',
    'list.aria': 'Фоновые задачи',
    'status.running': 'выполняется',
    'status.stopping': 'останавливается',
    'status.completed': 'завершена',
    'status.killed': 'отменена',
    'status.failed': 'ошибка',
    'duration.seconds': '{seconds} с',
    'duration.minutes': '{minutes} мин {seconds} с',
    'duration.hours': '{hours} ч {minutes} мин',
    'duration.title.live': 'Выполняется {duration}',
    'duration.title.done': 'Заняло {duration}',
  },
  'feedback': {
    'action.like': 'Хороший ответ',
    'action.likeActive': 'Снять оценку',
    'action.dislike': 'Плохой ответ',
    'action.dislikeActive': 'Снять оценку',
    'note.open': 'Добавить заметку',
    'note.dialog': 'Отзыв',
    'note.placeholder': 'Что было хорошо, а что не так? (необязательно)',
    'note.save': 'Сохранить',
    'note.cancel': 'Отмена',
    'note.aria': 'Заметка об отзыве',
    'error.conflict': 'Этот отзыв изменён в другом месте; показано актуальное состояние',
    'error.load': 'Не удалось загрузить отзыв',
    'error.generic': 'Не удалось сохранить отзыв',
  },
  'model': {
    'command.description': 'Выбор модели для этого диалога',
    'option.loadError': 'Не удалось загрузить каталог: {message}',
    'trigger.fallback': 'Выбрать модель',
    'trigger.loading': 'Загрузка моделей…',
    'trigger.selectAria': 'Выбрать модель',
    'trigger.aria': 'Выбрать модель, сейчас {model}',
    'trigger.ariaEffort': 'Выбрать модель, сейчас {model}, уровень рассуждения {effort}',
    'menu.aria': 'Модель и уровень рассуждения',
    'menu.model': 'Модель',
    'menu.effort': 'Уровень рассуждения',
    'effort.providerDefault': 'По умолчанию',
    'status.loading': 'Обновление списка моделей…',
    'error.action': 'Не удалось выполнить операцию с моделью: {message}',
    'action.reload': 'Перезагрузить',
    'warning.groupLoad': 'Не удалось загрузить {name}: {message}',
    'empty.models': 'Нет доступных моделей.',
    'blocked.composer': 'Эта модель недоступна — выберите другую, чтобы продолжить',
    'empty.efforts': 'У этой модели нет уровней рассуждения.',
  },
  'settings.permission': {
    'title': 'Права доступа',
    'description': 'Выберите режим прав по умолчанию для новых сессий',
    'loading': 'Загрузка',
    'unavailable': 'Недоступно',
    'preset.readOnly': 'Только чтение',
    'preset.workspaceWrite': 'Запись в рабочую папку',
    'preset.fullAccess': 'Полный доступ',
    'confirm.title': 'Включить «Полный доступ»?',
    'confirm.description': '«Полный доступ» позволяет новым сессиям пропускать шаги подтверждения и выполнять больше действий напрямую, включая чувствительные операции, изменение файлов или внешние команды. Используйте его, только если доверяете последующим задачам.',
    'confirm.acknowledge': 'Я понимаю риски и хочу продолжить',
    'confirm.cancel': 'Отмена',
    'confirm.enable': 'Включить «Полный доступ»',
  },
  'permission.access': {
    'preset.readOnly': 'Только чтение',
    'preset.workspaceWrite': 'Запись в рабочую папку',
    'preset.fullAccess': 'Полный доступ',
    'confirm.title': 'Включить «Полный доступ»?',
    'confirm.description': '«Полный доступ» уменьшает число этапов подтверждения и позволяет агенту напрямую выполнять больше действий, включая чувствительные операции, изменение файлов или внешние команды. Используйте его, только если доверяете текущей задаче.',
    'confirm.acknowledge': 'Я понимаю риски и хочу продолжить',
    'confirm.cancel': 'Отмена',
    'confirm.enable': 'Включить «Полный доступ»',
  },
  'plan': {
    'chip.label': 'План',
    'chip.on.aria': 'Режим планирования включён, нажмите, чтобы выключить',
    'chip.on.title': 'Режим планирования включён — нажмите, чтобы выключить (/plan off)',
    'chip.off.aria': 'Режим планирования выключен, нажмите, чтобы включить',
    'chip.off.title': 'Режим планирования выключен — нажмите, чтобы включить (/plan)',
    'chip.exitFailed': 'Не удалось выйти из режима планирования',
  },
  'reference': {
    'section.files': 'Файлы и папки',
    'section.sessions': 'Сессии',
    'candidate.noCwd': '(нет рабочей папки)',
    'crumb.root': 'Рабочая папка',
    'time.now': 'сейчас',
    'time.minutes': '{n} мин',
    'time.hours': '{n} ч',
    'time.days': '{n} д',
    'time.months': '{n} мес',
    'time.years': '{n} г',
  },
  'schedule.catalog': {
    'trigger.one': '{count} напоминание',
    'trigger.other': '{count} напоминаний',
    'list.aria': 'Активные напоминания',
    'status.scheduled': 'Запланировано',
    'status.overdue': 'Просрочено',
    'frequency.once': 'Однократно',
    'frequency.every': 'Каждые {value} {unit}',
    'unit.day.one': 'день',
    'unit.day.other': 'дней',
    'unit.hour.one': 'час',
    'unit.hour.other': 'часов',
    'unit.minute.one': 'минута',
    'unit.minute.other': 'минут',
    'unit.second.one': 'секунда',
    'unit.second.other': 'секунд',
    'relative.now': 'Срок наступил',
    'relative.future': 'через {value} {unit}',
    'relative.overdue': 'Просрочено на {value} {unit}',
  },
  'settings': {
    'trigger': 'Настройки',
    'title': 'Настройки',
    'close': 'Закрыть',
    'openDocument': 'Открыть файл конфигурации',
    'openDocument.error': 'Не удалось открыть файл конфигурации',
    'general.nav': 'Основные',
    'connection.error': 'Отключено',
    'connection.retry': 'Подключиться сейчас',
    'connection.connecting': 'Подключение',
    'connection.connected': 'Подключено',
    'connection.reconnect': 'Отключено, подключиться сейчас',
    'connection.restart': 'Подключение, перезапустить сейчас',
  },
  'settings.models': {
    'nav': 'Модели',
    'title': 'Модели',
    'intro': 'Введите API-ключи, чтобы использовать модели указанных провайдеров.',
    'edit': 'Изменить',
    'editProvider': 'Изменить {provider}',
    'remove': 'Удалить',
    'removeProvider': 'Удалить {provider}',
    'deleteTitle': 'Удалить {provider}?',
    'deleteDescription': 'Удаление {provider} уберёт его конфигурацию. Используемые им учётные данные управляются отдельно и будут сохранены.',
    'deleteDescriptionWithCredential': 'Удаление {provider} уберёт его конфигурацию и сохранённый API-ключ.',
    'deleteConfirm': 'Удалить {provider}',
    'deleting': 'Удаление {provider}…',
    'add': 'Добавить провайдера',
    'provider': 'Провайдер',
    'close': 'Закрыть',
    'cancel': 'Отмена',
    'apply': 'Применить',
    'applying': 'Применение…',
    'savedProvider': 'Сохранено: {provider}.',
    'credentialConfigured': 'API-ключ настроен',
    'credentialMissing': 'API-ключ отсутствует',
    'readOnly': 'Документ настроек в этой сборке доступен только для чтения.',
    'loadFailed': 'Не удалось загрузить каталог провайдеров',
    'conflict': 'Пока эта карточка была открыта, настройки изменились в другом месте. Закройте её и откройте заново, чтобы редактировать актуальные значения.',
    'retry': 'Повторить',
    'keyInput': 'API-ключ',
    'keyPlaceholder': 'Введите API-ключ',
    'keyPlaceholderNative': 'Введите API-ключ или оставьте поле пустым, чтобы использовать аутентификацию из окружения',
    'keyStored': 'Настроен — введите новое значение, чтобы заменить',
    'keyEnvLocked': 'Предоставлен окружением запуска (только для чтения)',
    'customized': 'Изменённые настройки',
    'baseUrl': 'Базовый URL',
    'baseUrlDefault': 'По умолчанию у провайдера',
    'models': 'Модели',
    'modelsInherited': 'Используются настройки адаптера по умолчанию',
    'modelsCustomized': 'Изменённый каталог моделей',
    'resetModels': 'Восстановить значения по умолчанию',
    'model': 'Модель',
    'modelId': 'ID модели',
    'modelName': 'Отображаемое имя',
    'modelNamePlaceholder': 'Если пусто — используется ID модели',
    'contextWindow': 'Контекстное окно',
    'contextWindowPlaceholder': 'Используется значение по умолчанию провайдера',
    'maxTokens': 'Максимум выходных токенов',
    'maxTokensPlaceholder': 'Используется значение по умолчанию провайдера',
    'modelAdvanced': 'Возможности',
    'addModel': 'Добавить модель',
    'removeModel': 'Удалить модель',
    'modelsEmpty': 'В селекторе не будет показано ни одной модели. ID вне списка можно отправлять напрямую.',
    'keyBlank': 'Введите API-ключ или оставьте поле пустым, чтобы сохранить имеющийся.',
    'keyBlankNew': 'Введите API-ключ или оставьте поле пустым, если провайдер использует другой способ аутентификации.',
    'keyIllegalCharacters': 'Формат этого API-ключа недействителен. Проверьте его.',
    'modelIdRequired': 'ID модели обязателен.',
    'modelIdDuplicate': 'ID модели должен быть уникальным.',
    'modelNameInvalid': 'Отображаемое имя не может быть пустым.',
    'modelContextInvalid': 'Контекстное окно должно быть положительным числом, например 131072, 256K или 1M.',
    'modelMaxTokensInvalid': 'Максимум выходных токенов должен быть положительным числом, например 8192, 64K или 1M.',
    'advancedHint': 'Остальные поля находятся в settings.yaml; редактируйте соответствующий раздел напрямую.',
    'modelCapacityInvalid': 'Возможность должна быть числом, при желании с суффиксом K или M.',
    'modelDuplicate': 'Каждый ID модели может встречаться только один раз.',
    'modelContextWindow': 'Контекстное окно',
    'modelMaxTokens': 'Максимум выходных токенов',
    'fetchModels': 'Получить доступные модели',
    'fetching': 'Запрос к провайдеру…',
    'fetchNeedsBaseUrl': 'Сначала введите базовый URL, затем получайте модели.',
    'fetchEmpty': 'Провайдер не указал модели. Добавьте их вручную.',
    'fetchTitle': 'Выберите модели для добавления',
    'fetchDescription': 'Это модели, доступные у провайдера. Выберите те, что нужно добавить.',
    'fetchSelectAll': 'Выбрать все',
    'fetchDeselectAll': 'Снять выбор',
    'fetchAdopt': 'Добавить выбранные',
    'customAdd': 'Добавить своего провайдера',
    'customTitle': 'Свой провайдер',
    'customTag': 'Свой',
    'customRoute': 'ID провайдера',
    'customRouteHint': 'Идентификатор в нижнем регистре, начинающийся с буквы; уникально именует провайдера в запросах и как имя учётных данных.',
    'customRouteInvalid': 'Начинайте с буквы в нижнем регистре; далее — буквы в нижнем регистре, цифры и дефисы.',
    'customRouteTaken': 'Этот ID уже использует другой провайдер.',
    'customDisplayName': 'Отображаемое имя',
    'customApi': 'Протокол API',
    'customApiUnset': 'Не выбран',
    'customNeedsBaseUrl': 'Своему провайдеру нужен базовый URL.',
    'customNeedsModels': 'Своему провайдеру нужна хотя бы одна модель.',
    'create': 'Создать провайдера',
    'creating': 'Создание…',
    'welcomeTitle': 'Уведомление о внутреннем тестировании',
    'welcomeBody': 'DeepSeek Harness 0.1 находится в стадии тестирования среди разработчиков Harness. Многие области ещё требуют доработки, и мы будем рады отзывам от сообщества разработчиков. Основные плагины и базовые API DeepSeek Harness будут активно развиваться в ближайшие месяцы.\n\nМы рассчитываем вместе с разработчиками по всему миру исследовать пределы возможностей интеллекта, опираясь на открытую, свободно используемую и компонуемую инфраструктуру. Приглашаем разработчиков Harness присоединиться к экосистеме плагинов DSH.',
    'welcomeContinue': 'Продолжить',
    'welcomeError': 'Не удалось сохранить подтверждение. Попробуйте ещё раз.',
    'onboardingTitle': 'Добавьте API-ключ, чтобы начать',
    'onboardingDescription': 'Настройте официального провайдера DeepSeek, чтобы начать работу.',
    'onboardingLater': 'Настроить позже',
    'onboardingSave': 'Сохранить и продолжить',
    'onboardingSaving': 'Сохранение…',
    'keyRequired': 'Введите API-ключ, чтобы продолжить.',
    'fetchSearch': 'Поиск моделей',
    'fetchNoMatches': 'Нет подходящих моделей.',
    'customBaseUrlPlaceholder': 'https://gateway.example/v1',
    'settingsPathUnresolvable': 'не удалось разрешить путь настроек',
  },
  'settings.pluginInventory': {
    'tab': 'Список плагинов',
    'loading': 'Чтение плагинов…',
    'error': 'Плагины временно недоступны.',
    'retry': 'Повторить',
    'search': 'Поиск плагинов',
    'empty': 'Нет доступных плагинов.',
    'emptySearch': 'Нет подходящих плагинов.',
    'enabledTag': 'Включён',
    'disabledTag': 'Отключён',
    'configuration': 'Конфигурация',
    'unobserved': 'Не подключён',
    'pending': 'Ожидание зависимостей',
    'loadingPhase': 'Загрузка',
    'active': 'Подключён',
    'failed': 'Ошибка подключения',
    'unloading': 'Отключение',
    'presetTitle': 'Плагины сессии',
    'presetSubtitle': 'Собираются для каждой сессии пресетами агента',
    'countUnit': 'плагины',
    'switcherLabel': 'Выберите пресет агента для просмотра',
    'presetOptionDefault': '{name} (по умолчанию)',
    'presetOptionBroken': '{name} (не удалось загрузить)',
    'globalTitle': 'Глобальные плагины',
    'globalSubtitle': 'Общие для системы и всех сессий',
    'presetProvidedDetail': 'Глобально отключён; пресеты агента включают его на уровне сессии',
    'enabledIn': 'Включён в',
    'viewInPreset': 'Открыть в группе пресета',
    'matchesInOtherPresets': 'Ещё совпадений в других пресетах: {count} ',
    'failedCountLabel': 'ошибок',
    'conditionalTag': 'Условно',
    'presetEnabledTag': 'Включён через пресеты',
    'failedTag': 'Сбой',
    'moduleLabel': 'Модуль',
    'fromPreset': 'Из',
    'condition': 'Отключается, когда',
    'runtime': 'Состояние',
  },
  'settings.plugins': {
    'nav': 'Плагины',
    'title': 'Плагины',
    'intro': 'Настройка и просмотр плагинов, установленных в этой сборке.',
    'tabs': 'Виды плагинов',
    'configurableTab': 'Конфигурация плагинов',
    'empty': 'Эта сборка не открывает настроек плагинов.',
    'overridden': 'Переопределено',
    'reset': 'Сбросить к значению по умолчанию',
    'readOnly': 'В этой сборке настройки хранятся только для чтения.',
    'expand': 'Показать настройки',
    'collapse': 'Скрыть настройки',
    'save': 'Сохранить',
    'saving': 'Сохранение…',
    'discard': 'Отменить изменения',
    'unsaved': 'Не сохранено',
    'saveFailed': 'Сборка не приняла эти значения; они оставлены для исправления.',
    'invalidNumber': 'Введите число или оставьте поле пустым, чтобы использовать значение по умолчанию.',
    'bashTitle': 'Терминал',
    'bashDescription': 'Ограничения для каждой команды, которую выполняет агент.',
    'bashTimeoutMs': 'Тайм-аут команды (мс)',
    'bashTimeoutMsHint': 'Сколько может выполняться одна команда, прежде чем будет завершена.',
    'bashMaxOutputBytes': 'Лимит вывода на поток (байт)',
    'bashMaxOutputBytesHint': 'Вывод сверх лимита сохраняется во временный файл, а не теряется.',
    'agentLoopTitle': 'Цикл агента',
    'agentLoopDescription': 'Как агент распределяет вызовы инструментов.',
    'agentLoopMaxParallel': 'Параллельные вызовы инструментов',
    'agentLoopMaxParallelHint': 'Верхний предел параллельных вызовов в пределах одного шага.',
    'webSearchTitle': 'Веб-поиск',
    'webSearchDescription': 'Поисковый провайдер DeepSeek.',
    'webSearchApiKey': 'API-ключ',
    'webSearchApiKeyHint': 'Хранится вне файла настроек. Оставьте пустым, чтобы сохранить текущий ключ.',
    'webSearchApiKeySet': 'Ключ настроен.',
    'webSearchApiKeyUnset': 'Ключ не настроен; поиск недоступен, пока он не будет добавлен.',
    'webSearchBaseUrl': 'Эндпоинт',
    'webSearchBaseUrlHint': 'Оставьте пустым, чтобы использовать адрес провайдера по умолчанию.',
    'webSearchMaxUses': 'Максимум поисков за запрос',
    'webSearchMaxUsesHint': 'Сколько раз один запрос может искать, прежде чем должен дать ответ.',
    'subagentModelSelectionTitle': 'Субагенты',
    'subagentModelSelectionDescription': 'Укажите, какие модели агенты могут выбирать для субагентов.',
    'subagentModelSelectionToggle': 'Разрешить агентам выбирать модели для субагентов',
    'subagentModelSelectionChoose': 'При включении агенты могут выбирать провайдера, модель и уровень рассуждения для каждого субагента из авторизованных моделей ниже. Применяется только к новым сессиям.',
    'subagentModelSelectionAllowed': 'Модели, доступные агентам для выбора',
    'subagentModelSelectionLoading': 'Загрузка моделей…',
    'subagentModelSelectionLoadFailed': 'Не удалось загрузить модели.',
    'subagentModelSelectionRetry': 'Повторить',
    'subagentModelSelectionPartial': 'Некоторые провайдеры моделей не загрузились; сохранённые выборки по-прежнему можно удалить.',
    'subagentModelSelectionUnavailable': 'Сейчас недоступно',
    'subagentModelSelectionUnavailableGroup': 'Сохранено, но сейчас недоступно',
    'subagentModelSelectionEmpty': 'Ни один провайдер моделей сейчас не предлагает моделей.',
    'subagentModelSelectionRequired': 'Перед сохранением выберите хотя бы одну модель.',
    'subagentModelSelectionConflict': 'Настройки изменены в другом месте. Отмените черновик и повторите.',
    'subagentModelSelectionOff': 'Субагенты используют настроенные значения по умолчанию или наследуют модель родительского агента. Сохранённые выборки моделей остаются.',
  },
  'sidebar': {
    'session.new': 'Новая сессия',
    'session.new.label': 'Новая сессия',
    'toggle.open': 'Открыть боковую панель',
    'toggle.collapse': 'Свернуть боковую панель',
  },
  'skill': {
    'row.title': 'Навык',
    'row.running': 'Загрузка навыка',
    'row.failed': 'Не удалось загрузить навык',
    'row.stopped': 'Загрузка навыка прервана',
    'row.instructions': 'Инструкции',
    'row.inspect': 'Просмотр',
    'menu.userOnly': 'только пользователь',
  },
  'subagent': {
    'diagnostic.corrupt': 'повреждённая запись сессии',
    'diagnostic.unsupported': 'неподдерживаемая версия записи субагента',
    'diagnostic.unavailable': 'запись сессии временно недоступна',
    'duration.seconds': '{seconds} с',
    'duration.minutes': '{minutes} мин {seconds} с',
    'duration.hours': '{hours} ч {minutes} мин {seconds} с',
    'duration.days': '{days} д',
    'duration.daysHours': '{days} д {hours} ч',
    'duration.months': '~{months} мес',
    'duration.monthsDays': '~{months} мес {days} д',
    'duration.years': '~{years} г',
    'duration.yearsMonths': '~{years} г {months} мес',
    'duration.exactDays': '{days} д {hours} ч {minutes} мин {seconds} с',
    'duration.exactTitle': 'Общее время активности: {duration}',
    'loading.label': 'Загрузка субагентов…',
    'loading.aria': 'Загрузка субагентов',
    'load.error': 'Не удалось загрузить субагентов',
    'retry': 'Повторить',
    'mode.oneShot': 'одноразовый',
    'mode.continuable': 'можно продолжить',
    'activity.running': 'выполняется',
    'activity.inactive': 'не выполняется',
    'branch.collapse': 'Свернуть потомков {label}',
    'branch.expand': 'Развернуть потомков {label}',
    'count.total.one': '{count} субагент',
    'count.total.other': '{count} субагентов',
    'count.running.one': '{count} субагент выполняется',
    'count.running.other': '{count} субагентов выполняется',
    'switcher.aria': 'Переключить субагента: {title}',
    'tree.aria': 'Сессии субагентов',
    'readonly.oneShot.title': 'Запись одноразового субагента',
    'readonly.title': 'Этот субагент пока доступен только для чтения',
    'readonly.oneShot.body': 'Одноразовые задачи не принимают продолжений; здесь можно посмотреть полную запись выполнения.',
    'readonly.body': 'Родительская сессия сейчас не в сети; откройте её заново, чтобы продолжить отправку сообщений.',
    'tokens.thousand': '{value} тыс.',
    'tokens.million': '{value} млн',
    'tokens.total': '{value} ток',
  },
  'settings.theme': {
    'appearance.title': 'Оформление',
    'appearance.light': 'Светлая',
    'appearance.dark': 'Тёмная',
    'appearance.system': 'Как в системе',
    'fontSize.title': 'Размер шрифта',
    'fontSize.description': 'Влияет только на содержимое беседы',
    'fontSize.unit': 'px',
    'fontSize.increase': 'Увеличить размер шрифта',
    'fontSize.decrease': 'Уменьшить размер шрифта',
  },
  'trajectory': {
    'view.trajectory': 'Траектория',
    'toolbar.aria': 'Панель траектории',
    'toolbar.duration': 'Длительность',
    'toolbar.useActualDuration': 'Фактическая длительность',
    'toolbar.useEqualWidth': 'Равная ширина операций',
    'toolbar.actualTime': 'Фактическое время',
    'toolbar.turns': 'Раунды',
    'toolbar.expandTurns': 'Развернуть раунды',
    'toolbar.collapseTurns': 'Свернуть раунды',
    'toolbar.calls': 'Вызовы',
    'toolbar.expandCalls': 'Развернуть вызовы',
    'toolbar.collapseCalls': 'Свернуть вызовы',
    'toolbar.search': 'Поиск по траектории',
    'toolbar.searchPlaceholder': 'Поиск',
    'column.input': 'Ввод',
    'column.model': 'Модель',
    'column.tools': 'Инструменты',
    'status.pending': 'Ожидает',
    'timing.notAvailable': 'Недоступно',
    'timing.notRecorded': 'Не записано',
    'timing.stepStartUnavailable': 'Недоступно время начала шага',
    'timing.firstTokenUnavailable': 'Недоступно время первого токена',
    'timing.usageUnavailable': 'Данные об использовании недоступны',
    'timing.outputTokensUnavailable': 'Недоступно число выходных токенов',
    'timing.durationTooShort': 'Длительность слишком мала',
    'timing.started': 'Начало',
    'timing.totalDuration': 'Общая длительность',
    'timing.ttft': 'TTFT',
    'timing.generation': 'Генерация',
    'timing.throughput': 'Пропускная способность',
    'timing.duration': 'Длительность',
    'timing.source': 'Источник времени',
    'timing.sessionTimestamps': 'Метки времени сессии',
    'timing.sessionTimestampsRunning': 'Метки времени сессии (выполняется)',
    'usage.input': 'Ввод',
    'tab.tools': 'Инструменты',
    'record.noContent': 'Нет содержимого',
    'record.noPayload': 'Ввод не зафиксирован',
    'record.noResult': 'Результат не зафиксирован',
    'record.resultJson': 'Результат JSON',
    'record.outputJson': 'Результат JSON',
    'record.thinking': 'Рассуждение',
    'record.tools': 'Инструменты',
    'block.openSummaryTitle': 'Открыть сводку вызова',
    'history.loadingEarlier': 'Загрузка более ранней истории…',
    'history.loadingEarlierAria': 'Загрузка более ранней истории…',
    'history.loadEarlier': 'Загрузить более раннюю историю',
    'history.clickToLoadEarlier': 'Нажмите, чтобы загрузить более раннюю историю',
    'details.event': 'Детали события',
    'details.resize': 'Изменить размер панели деталей',
    'details.resizeTitle': 'Перетащите, чтобы изменить размер. Двойной клик — сброс.',
    'details.close': 'Закрыть детали',
    'details.model': 'Модель',
    'timeline.aria': 'Таймлайн траектории',
    'timeline.overviewAria': 'Обзор таймлайна; перетаскивайте по горизонтали, чтобы фокусироваться на событиях',
    'timeline.noTimingData': 'Нет данных о времени',
    'timeline.total': 'Всего: {duration}',
    'timeline.started': 'Начало: {time}',
    'layout.toolCallOnly': 'Только вызов инструмента',
    'kind.system': 'SYSTEM',
    'kind.user': 'USER',
    'kind.context': 'CONTEXT',
    'kind.compacted': 'COMPACTED',
    'kind.message': 'Сообщение',
    'kind.assistant': 'ASSISTANT',
    'kind.tool': 'TOOL',
    'kind.subtool': 'SUBTOOL',
    'kind.sub': 'Sub',
    'column.output': 'Вывод',
    'column.think': 'Размышление',
    'column.time': 'Время',
    'turn.label': 'Ход {turn}',
    'section.betweenTurns': 'Между ходами',
    'group.message': 'Сообщение',
    'group.step': 'Шаг {step}',
    'group.compaction': 'Сжатие {seq}',
    'status.failed': 'Ошибка',
    'status.completed': 'Завершено',
    'timing.showLocalTime': 'Показать локальное время',
    'timing.showUnixTimestamp': 'Показать Unix-метку времени',
    'timing.request': 'Время запроса',
    'unit.milliseconds': '{value} мс',
    'unit.seconds': '{value} с',
    'unit.tokens': '{value} ток',
    'unit.tokensPerSecond': '{value} ток/с',
    'usage.tokens': 'Токены',
    'usage.reasoning': 'Размышление',
    'usage.content': 'Содержимое',
    'usage.notReported': 'Данные об использовании не сообщаются',
    'usage.cached': 'Из кэша',
    'usage.cacheCreated': 'Запись в кэш',
    'usage.other': 'Прочее',
    'usage.output': 'Выход',
    'usage.thisRequest': 'Этот запрос',
    'usage.sessionCumulative': 'Суммарно по сессии',
    'options.notRecorded': 'Параметры не записаны',
    'options.json': 'JSON параметров запроса',
    'source.unknown': 'Неизвестно',
    'source.user': 'Пользователь',
    'source.plugin': 'Плагин',
    'source.pluginNamed': 'Плагин · {plugin}',
    'source.goal': 'Цель',
    'source.goalRound': 'Цель · Раунд {round}',
    'source.notRecorded': 'Источник не записан',
    'source.messageJson': 'JSON источника сообщения',
    'tab.summary': 'Сводка',
    'tab.rawOutput': 'Исходный вывод',
    'tab.preview': 'Предпросмотр',
    'tab.raw': 'Исходный текст',
    'tab.source': 'Источник',
    'tab.payload': 'Запрос',
    'tab.result': 'Результат',
    'tab.schema': 'Схема',
    'tab.timing': 'Время',
    'tab.diff': 'Дифф',
    'tab.systemPrompt': 'Системный промпт',
    'tab.options': 'Параметры',
    'tab.usage': 'Использование',
    'record.toolCallOnly': '(только вызов инструмента)',
    'record.noOutput': 'Нет вывода',
    'record.schemaUnavailable': 'Схема недоступна',
    'record.parameters': 'Параметры',
    'record.json': 'JSON',
    'record.parametersJson': 'JSON параметров',
    'record.namedParametersJson': 'JSON параметров {name}',
    'record.payloadJson': 'JSON запроса',
    'record.systemPromptMissing': 'В этом запросе нет системного промпта',
    'record.toolsMissing': 'В этом запросе нет инструментов',
    'record.systemPrompt': 'Системный промпт',
    'block.openSummary': 'Открыть сводку вызова инструментов для блока #{index}',
    'block.label': 'Блок #{index} {type}',
    'history.loadingTrajectory': 'Загрузка траектории…',
    'request.label': 'Запрос #{request}',
    'request.labelCompaction': 'Запрос #{request} · Сжатие',
    'request.compaction': 'Сжатие · {section}',
    'request.compactionPurpose': 'Сжатие',
    'request.retryProgress': '{retry} из {maximum}',
    'request.collapsedSummary': 'Свёрнутая сводка {kind}, {summary}',
    'request.collapsedTurn': 'хода',
    'request.collapsedAssistant': 'ассистента',
    'request.rowAria': '{request}{kind}, {content}',
    'request.rowPrefix': 'Запрос {request}, ',
    'request.rowAriaCompaction': 'Запрос {request}, сжатие',
    'request.noContent': 'нет содержимого',
    'summary.toolCalls.one': '{count} вызов инструмента',
    'summary.toolCalls.other': '{count} вызовов инструментов',
    'summary.steps.one': '{count} шаг',
    'summary.steps.other': '{count} шагов',
    'details.status': 'Состояние',
    'details.purpose': 'Назначение',
    'details.provider': 'Провайдер',
    'details.toolCalls': 'Вызовы инструментов',
    'details.subtoolCalls': 'Вложенные вызовы',
    'details.error': 'Ошибка',
    'details.failure.auth': 'Недействительный API-ключ',
    'details.retry': 'Повтор',
    'details.scheduled': 'Запланирован',
    'details.retryDelay': 'Задержка повтора',
    'details.result': 'Результат',
    'details.compacted': 'Сжато',
    'details.assistantMessage': 'Сообщение ассистента',
    'details.source': 'Источник',
    'details.hierarchy': 'Иерархия',
    'details.toolCall': 'Вызов инструмента',
    'timeline.ttftDecoding': 'TTFT {ttft} · Декодирование {decoding}',
    'layout.compacting': 'Сжатие контекста…',
    'layout.compactionFailed': 'Сжатие не удалось',
    'layout.compacted': 'Контекст сжат',
    'layout.imageOnly': 'Изображения ×{count}',
    'layout.initialSystemPrompt': 'Начальный системный промпт',
    'layout.systemPromptUpdated': 'Системный промпт обновлён',
    'layout.toolsUpdated': 'Инструменты обновлены',
    'layout.systemPromptAndToolsUpdated': 'Системный промпт и инструменты обновлены',
    'layout.compactionInterrupted': 'Сжатие было прервано до завершения.',
  },
  'question': {
    'error.incomplete': 'Сначала завершите этот вопрос.',
    'error.unanswered': 'Выберите вариант или введите свой ответ.',
    'nav.prev': 'Предыдущий вопрос',
    'nav.next': 'Следующий вопрос',
    'nav.minimize': 'Свернуть карточку вопроса',
    'nav.maximize': 'Развернуть карточку вопроса',
    'nav.cancel': 'Отменить все вопросы',
    'option.recommended': 'Рекомендуется',
    'custom.placeholder': 'Введите ваш ответ',
    'action.skip': 'Пропустить вопрос',
    'action.next': 'Далее',
    'plan.header': 'План на рассмотрении',
    'plan.approve': 'Утвердить',
    'plan.decline': 'Отклонить',
    'plan.discuss': 'Обсудить в чате',
  },
  'workflowRun': {
    'run.title': '{name}',
    'run.members.one': '{count} участник',
    'run.members.other': '{count} участников',
    'run.empty': 'Участники не запущены',
    'phase.unassigned': 'Без фазы',
    'phase.empty': 'Пустое имя фазы',
    'statusCount.running': 'Выполняется: {count}',
    'statusCount.completed': 'Завершено: {count}',
    'statusCount.failed': 'Ошибка: {count}',
    'statusCount.cancelled': 'Отменено: {count}',
    'statusCount.interrupted': 'Прервано: {count}',
    'member.empty': 'Пустое имя участника',
    'member.open': 'Открыть {name}',
    'status.running': 'Выполняется',
    'status.completed': 'Завершено',
    'status.failed': 'Ошибка',
    'status.cancelled': 'Отменено',
    'status.interrupted': 'Прервано',
  },
  'workspace': {
    'group.ungrouped': 'Без группы',
    'session.new': 'Новая сессия',
    'section.workspaces': 'Рабочие пространства',
    'section.sessions': 'Сессии',
    'viewOptions.label': 'Параметры вида',
    'groupBy.label': 'Группировка',
    'groupBy.workspace': 'По рабочим пространствам',
    'groupBy.flat': 'Единым списком',
    'orderBy.label': 'Сортировка',
    'orderBy.manual': 'Вручную',
    'orderBy.updated': 'По обновлению',
    'sessions.expand': 'Показать ещё {n}',
    'sessions.collapse': 'Свернуть',
    'empty.none': 'Пока нет сессий',
    'empty.noMatches': 'Ничего не найдено',
    'workspace.add': 'Добавить рабочее пространство',
    'search.sessions.aria': 'Поиск сессий',
    'search.placeholder': 'Поиск сессий…',
    'search.clear': 'Очистить поиск',
    'search.results.aria': 'Результаты поиска',
    'search.pending': 'Поиск по истории сессий…',
    'search.unavailable': 'Контентный поиск временно недоступен. Показываем совпадения по имени.',
    'search.noMatches': 'Нет подходящих сессий',
    'search.hasMore': 'Показаны первые {n}. Сузьте поиск.',
    'menu.addWorkspace': 'Добавить рабочее пространство…',
    'picker.loading': 'Загрузка рабочих пространств…',
    'conflict.named': 'Рабочее пространство с именем «{name}» уже существует.',
    'folderError.title': 'Не удалось открыть папку',
    'folderError.retry': 'Выбрать снова',
    'rename': 'Переименовать',
    'rename.workspace.title': 'Переименовать рабочее пространство',
    'rename.session.title': 'Переименовать сессию',
    'field.workspaceName': 'Имя рабочего пространства',
    'field.sessionName': 'Имя сессии',
    'delete.workspace': 'Удалить рабочее пространство',
    'delete.desc': 'Это удалит «{name}» из списка рабочих пространств. Папка и журналы сессий сохранятся; их сессии появятся в разделе «Без группы».',
    'delete.pending': 'Удаление рабочего пространства…',
    'menu.fork': 'Создать ответвление сессии',
    'menu.archiveSession': 'Архивировать сессию',
    'sessions.count.one': '{n} сессия',
    'sessions.count.other': '{n} сессий',
    'actions.workspace.aria': 'Действия рабочего пространства {name}',
    'actions.session.aria': 'Действия сессии {name}',
    'actions.newSession.aria': 'Новая сессия в {name}',
    'status.running': 'Выполняется',
    'status.subagentsRunning.one': '{n} субагент выполняется',
    'status.subagentsRunning.other': '{n} субагентов выполняется',
    'status.idle': 'Ожидает',
    'status.waitingApproval': 'Ожидает одобрения',
    'status.planReview': 'План на рассмотрении',
    'status.waitingAnswer': 'Ожидает ответа',
    'status.completed': 'Завершено',
    'schedule.active': 'Есть активная запланированная задача',
    'hover.created': 'Создано {time}',
    'hover.copied': 'Скопировано',
    'date.ymd': '{d}.{m}.{y}',
    'time.now': 'только что',
    'time.minutes': '{n} мин',
    'time.hours': '{n} ч',
    'time.days': '{n} д',
    'time.months': '{n} мес',
    'time.years': '{n} г',
    'time.ago': '{t} назад',
  },
  'agent-team': {
    'memberStatus.running': 'Выполняется',
    'memberStatus.idle': 'Простой',
    'memberStatus.inactive': 'Неактивен',
    'memberStatus.provisioning': 'Подготовка',
    'memberStatus.failed': 'Ошибка',
    'status.pending': 'Ожидание',
    'status.in_progress': 'В процессе',
    'status.completed': 'Завершено',
    'trigger': 'Команда агентов',
    'refresh': 'Обновить команду',
    'close': 'Закрыть',
    'loading': 'Загрузка команды…',
    'empty': 'Общих задач пока нет',
    'roster': 'Участники',
    'tasks': 'Общие задачи',
    'model': 'Модель',
    'open': 'Открыть диалог с участником',
    'create': 'Новая задача',
    'subject': 'Тема задачи',
    'description': 'Описание задачи',
    'blockers': 'ID блокирующих задач (через запятую)',
    'scopes': 'Области записи (через запятую)',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'edit': 'Изменить',
    'complete': 'Завершить',
    'reopen': 'Открыть заново',
    'delete': 'Удалить',
    'owner': 'Исполнитель',
    'unowned': 'Без исполнителя',
    'blockedBy': 'Блокируется',
    'writeScopes': 'Области записи',
    'ready': 'Готово к работе',
    'blocked': 'Заблокировано зависимостями',
    'conflict': 'Состояние задачи изменилось, она перезагружена. Проверьте её перед повтором.',
  },
  'cordis': {
    'row.defineTitle': 'Зарегистрировать плагин Cordis',
    'row.runTitle': 'Запустить плагин Cordis',
    'row.updateTitle': 'Обновить плагин Cordis',
    'row.stopTitle': 'Остановить плагин Cordis',
    'row.removeTitle': 'Удалить плагин Cordis',
    'purpose.missing': '(цель не указана)',
    'status.idle': 'Готов',
    'status.awaitingApproval': 'Ожидает одобрения',
    'status.failed': 'Ошибка запуска',
    'status.clientPending': 'Client готов к активации',
    'status.running': 'Выполняется',
    'status.removed': 'Удалён',
    'status.superseded': 'Доступен более новый запуск',
    'run.removed': 'Этого пакета больше не существует',
    'run.superseded': 'Ниже доступна более новая карточка запуска',
    'panel.hint': 'Управление запуском находится на панели Cordis над настройками',
    'panel.plugins.aria': 'Плагины Cordis',
    'panel.approvals.aria': 'Одобрения Cordis',
    'panel.trigger': 'Плагин Cordis',
    'panel.runningCount': '{count} в работе',
    'panel.title': 'Плагины Cordis',
    'panel.empty': 'Плагины ещё не определены',
    'panel.loading': 'Чтение…',
    'panel.readFailed': 'Не удалось прочитать список плагинов: {message}',
    'panel.group.current': 'Эта сессия',
    'panel.group.others': 'Другие сессии',
    'panel.version': 'Версия',
    'panel.current': 'Текущая: {packageId}',
    'panel.next': 'Следующая: {packageId}',
    'action.approve': 'Разрешить',
    'action.approveOnce': 'Разрешить только эту версию',
    'action.approvePlugin': 'Разрешить будущие версии этого плагина',
    'action.decline': 'Отклонить',
    'action.run': 'Запустить',
    'action.stop': 'Остановить',
    'action.remove': 'Удалить',
    'action.retry': 'Повторить',
    'action.rollback': 'Откатить',
    'action.inspect': 'Просмотр',
    'render.failedAbdicated': 'Сбой рендеринга в {slot}; восстановлен интерфейс по умолчанию:',
    'render.failedHeld': 'Сбой рендеринга в {slot}:',
    'a11y.defining': 'Идёт определение плагина',
    'a11y.failed': 'Определение не удалось',
    'a11y.stopped': 'Определение прервано',
    'body.source': 'Исходный код плагина',
    'body.hostCode': 'Хост',
    'body.clientCode': 'Клиент',
    'body.output': 'Результат',
    'body.copy': 'Копировать',
    'body.copied': 'Скопировано',
  },
  'session-log-download': {
    'header.action': 'Журнал сессии',
    'dialog.preparingTitle': 'Экспорт сессии',
    'dialog.preparingDescription': 'Готовится ZIP-архив с этой сессией, её подсессиями и вложениями.',
    'dialog.successTitle': 'Загрузка сессии началась',
    'dialog.successDescription': 'Браузер загружает ZIP-архив сессии.',
    'dialog.errorTitle': 'Не удалось экспортировать сессию',
    'dialog.close': 'Закрыть',
    'dialog.commandFailed': 'Не удалось запустить экспорт сессии.',
  },
  'chat': {
    'view.chat': 'Чат',
    'number.groupSeparator': ' ',
    'duration.compactSeconds': '{seconds} с',
    'duration.compactMinutes': '{minutes} мин {seconds} с',
    'duration.milliseconds': '{milliseconds} мс',
    'stats.counts': '{turns} ходов · {steps} шагов',
    'stats.llm': 'LLM {duration}',
    'stats.toolCall': 'Вызов инструмента {duration}',
    'stats.ttftAverage': 'Среднее время до первого токена: {duration}',
    'stats.tokensPerSecond': '{throughput} ток/с',
    'stats.cacheHit': 'Попадание в кэш {percent}%',
    'stats.tokens': 'Вход {input} ток · Выход {output} ток',
    'details.title': 'Подробности',
    'details.close': 'Закрыть подробности',
    'details.empty': 'Нажмите на строку инструмента в потоке сообщений, чтобы увидеть подробности',
    'details.notInWindow': 'Этот вызов вне текущего окна',
    'details.input': 'Ввод',
    'details.output': 'Вывод',
    'details.running': 'Выполняется…',
    'chat.loadingHistory': 'Загрузка истории…',
    'chat.loadError': 'Не удалось загрузить историю: {message} ({code})',
    'chat.loadOlder': 'Загрузить ранее',
    'chat.toBottom': 'Вниз',
    'chat.deepDiving': 'Глубокое исследование…',
    'chat.turnNavigation.label': 'Навигация по ходам',
    'chat.turnNavigation.jump': 'Перейти к ходу {turn}',
    'chat.turnNavigation.jumpLoad': 'Загрузить и перейти к ходу {turn}',
    'chat.turnNavigation.turn': 'Ход {turn}',
    'settings.transcript.title': 'Отображение диалога',
    'settings.transcript.description': 'Управляет содержимым процесса в завершённых ходах',
    'settings.transcript.normal': 'Обычный',
    'settings.transcript.compact': 'Компактный',
    'fileOpen.title': 'Не удалось открыть файл',
    'fileOpen.unknown': 'Не удалось открыть этот файл',
    'fileOpen.folderTitle': 'Не удалось открыть папку',
    'fileOpen.folderUnknown': 'Не удалось открыть эту папку',
    'message.extraBlock': 'Дополнительный блок содержимого',
    'message.systemPrompt': 'Системный промпт',
    'message.contextInjection': 'Инъекция контекста',
    'message.contextRecall': 'Межсессонный поиск',
    'message.referenceSummary': 'Ссылка на сессию · {labels}',
    'message.referenceSeparator': ', ',
    'message.context.instructions.loaded': 'загружено',
    'message.context.instructions.added': 'добавлено',
    'message.context.instructions.updated': 'обновлено',
    'message.context.instructions.removed': 'удалено',
    'message.context.catalog.replaced': 'Заменённый каталог',
    'message.context.catalog.more': '… ещё {count}',
    'message.context.snapshot.supersedes': 'Заменяет предыдущие снимки',
    'message.context.relay.from': 'Из сессии {session}',
    'message.context.recall.counts': 'Сохранено {retained} · Пропущено {omitted}',
    'message.context.recall.truncated': 'обрезано',
    'message.compaction': 'Контекст сжат',
    'message.compaction.running': 'Сжатие контекста…',
    'message.compaction.completed': 'Сжато {items} записей истории (~{tokens} токенов)',
    'message.compaction.expand': 'Показать сводку сжатия',
    'message.compaction.unavailable': 'Сводка сжатия недоступна',
    'message.compaction.commandTitle': 'compact',
    'message.think': 'Размышление',
    'message.unknownSurface': 'Неизвестное surface-событие: {type}',
    'message.unknownBlock': 'Неизвестный блок содержимого',
    'message.turnProcess.toolCalls.one': '{count} вызов инструмента',
    'message.turnProcess.toolCalls.other': '{count} вызовов инструментов',
    'message.turnProcess.messages.one': '{count} сообщение',
    'message.turnProcess.messages.other': '{count} сообщений',
    'message.turnProcess.subagents.one': '{count} субагент',
    'message.turnProcess.subagents.other': '{count} субагентов',
    'message.turnProcess.thoughtForAWhile': 'Думал некоторое время',
    'message.turnProcess.separator': ' · ',
    'message.stopped': 'Остановлено',
    'message.branch': 'Ответвить новый диалог',
    'message.branchUnavailable': 'Доступно только на последнем сообщении завершённого хода',
    'message.retry.active': 'Повтор запроса к модели',
    'message.retry.cancelled': 'Повтор запроса к модели отменён',
    'message.retry.started': 'Запрос к модели повторён',
    'message.retry.scheduled': 'Ожидание повтора запроса к модели',
    'message.retry.status': '{label} ({retry}/{maximum}) · {seconds} с',
    'message.retry.delay': 'Задержка повтора: ',
    'message.retry.failure': 'Причина сбоя: ',
    'message.failure.auth': 'Недействительный API-ключ',
    'message.turnError': 'Этот ход завершился с ошибкой',
    'message.maxTokens': 'Достигнут лимит выходных токенов',
    'message.maxTokens.hint': 'Ответ обрезан; уже выведенное сохранено в диалоге. Отправьте «продолжай», чтобы модель завершила ответ.',
    'message.ranFor': 'Выполнялся {duration}',
    'message.tokensPerSecond': '{tps} ток/с',
    'message.turnUsage.title': 'Расход хода',
    'message.turnUsage.consumed': 'Расход {total}',
    'message.turnUsage.model': 'Провайдер / модель',
    'message.turnUsage.cacheHit': 'Попадание в кэш',
    'message.turnUsage.input': 'Вход без кэша',
    'message.turnUsage.cacheRead': 'Чтение из кэша',
    'message.turnUsage.cacheWrite': 'Запись в кэш',
    'message.turnUsage.output': 'Выход',
    'message.turnUsage.reasoning': ' (из них размышление {tokens})',
    'message.turnUsage.count': '{count} ток',
    'message.turnTime.title': 'Время и скорость хода',
    'message.turnTime.duration': 'Общее время хода',
    'message.turnTime.speed': 'Скорость вывода (TPS)',
    'message.turnTime.ttft': 'Время до первого токена (TTFT)',
    'duration.seconds': '{seconds} с',
    'duration.minutes': '{minutes} мин {seconds} с',
    'command.running': 'Выполняется…',
    'command.failed': 'Команда завершилась с ошибкой',
    'command.done': 'Завершено',
    'command.title': 'Команда',
    'row.running': 'Выполняется',
    'row.failed': 'Ошибка',
    'json.truncated': '… обрезано, всего {total} символов',
    'clock.md': '{d}.{m}',
    'clock.ymd': '{d}.{m}.{y}',
  },
  'directory-browser': {
    'browser.title': 'Выбор рабочего каталога',
    'browser.home': 'Домой',
    'browser.newFolder': 'Новая папка',
    'browser.folderName': 'Имя папки',
    'browser.createIn': 'Новая папка в "{name}"',
    'browser.untitledFolder': 'Папка без имени',
    'browser.create': 'Создать',
    'browser.cancel': 'Отмена',
    'browser.open': 'Открыть',
    'browser.editPath': 'Изменить путь',
    'browser.loading': 'Загрузка…',
    'browser.truncated': 'Слишком много папок; показано только начало списка.',
    'browser.showHidden': 'Показывать скрытые файлы',
  },
}
